//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace QuantLib {

public class FdG2SwaptionEngine : PricingEngine {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal FdG2SwaptionEngine(global::System.IntPtr cPtr, bool cMemoryOwn) : base(NQuantLibcPINVOKE.FdG2SwaptionEngine_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FdG2SwaptionEngine obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~FdG2SwaptionEngine() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NQuantLibcPINVOKE.delete_FdG2SwaptionEngine(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public FdG2SwaptionEngine(ShortRateModel model, uint tGrid, uint xGrid, uint yGrid, uint dampingSteps, double invEps, FdmSchemeDesc schemeDesc) : this(NQuantLibcPINVOKE.new_FdG2SwaptionEngine__SWIG_0(ShortRateModel.getCPtr(model), tGrid, xGrid, yGrid, dampingSteps, invEps, FdmSchemeDesc.getCPtr(schemeDesc)), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public FdG2SwaptionEngine(ShortRateModel model, uint tGrid, uint xGrid, uint yGrid, uint dampingSteps, double invEps) : this(NQuantLibcPINVOKE.new_FdG2SwaptionEngine__SWIG_1(ShortRateModel.getCPtr(model), tGrid, xGrid, yGrid, dampingSteps, invEps), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public FdG2SwaptionEngine(ShortRateModel model, uint tGrid, uint xGrid, uint yGrid, uint dampingSteps) : this(NQuantLibcPINVOKE.new_FdG2SwaptionEngine__SWIG_2(ShortRateModel.getCPtr(model), tGrid, xGrid, yGrid, dampingSteps), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public FdG2SwaptionEngine(ShortRateModel model, uint tGrid, uint xGrid, uint yGrid) : this(NQuantLibcPINVOKE.new_FdG2SwaptionEngine__SWIG_3(ShortRateModel.getCPtr(model), tGrid, xGrid, yGrid), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public FdG2SwaptionEngine(ShortRateModel model, uint tGrid, uint xGrid) : this(NQuantLibcPINVOKE.new_FdG2SwaptionEngine__SWIG_4(ShortRateModel.getCPtr(model), tGrid, xGrid), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public FdG2SwaptionEngine(ShortRateModel model, uint tGrid) : this(NQuantLibcPINVOKE.new_FdG2SwaptionEngine__SWIG_5(ShortRateModel.getCPtr(model), tGrid), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public FdG2SwaptionEngine(ShortRateModel model) : this(NQuantLibcPINVOKE.new_FdG2SwaptionEngine__SWIG_6(ShortRateModel.getCPtr(model)), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
