//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace QuantLib {

public class FxSwapRateHelper : RateHelper {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal FxSwapRateHelper(global::System.IntPtr cPtr, bool cMemoryOwn) : base(NQuantLibcPINVOKE.FxSwapRateHelper_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FxSwapRateHelper obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~FxSwapRateHelper() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          NQuantLibcPINVOKE.delete_FxSwapRateHelper(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public FxSwapRateHelper(QuoteHandle fwdPoint, QuoteHandle spotFx, Period tenor, uint fixingDays, Calendar calendar, BusinessDayConvention convention, bool endOfMonth, bool isFxBaseCurrencyCollateralCurrency, YieldTermStructureHandle coll, Calendar tradingCalendar) : this(NQuantLibcPINVOKE.new_FxSwapRateHelper__SWIG_0(QuoteHandle.getCPtr(fwdPoint), QuoteHandle.getCPtr(spotFx), Period.getCPtr(tenor), fixingDays, Calendar.getCPtr(calendar), (int)convention, endOfMonth, isFxBaseCurrencyCollateralCurrency, YieldTermStructureHandle.getCPtr(coll), Calendar.getCPtr(tradingCalendar)), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public FxSwapRateHelper(QuoteHandle fwdPoint, QuoteHandle spotFx, Period tenor, uint fixingDays, Calendar calendar, BusinessDayConvention convention, bool endOfMonth, bool isFxBaseCurrencyCollateralCurrency, YieldTermStructureHandle coll) : this(NQuantLibcPINVOKE.new_FxSwapRateHelper__SWIG_1(QuoteHandle.getCPtr(fwdPoint), QuoteHandle.getCPtr(spotFx), Period.getCPtr(tenor), fixingDays, Calendar.getCPtr(calendar), (int)convention, endOfMonth, isFxBaseCurrencyCollateralCurrency, YieldTermStructureHandle.getCPtr(coll)), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

  public FxSwapRateHelper(QuoteHandle fwdPoint, QuoteHandle spotFx, Period tenor, uint fixingDays, Calendar calendar, BusinessDayConvention convention, bool endOfMonth, bool isFxBaseCurrencyCollateralCurrency) : this(NQuantLibcPINVOKE.new_FxSwapRateHelper__SWIG_2(QuoteHandle.getCPtr(fwdPoint), QuoteHandle.getCPtr(spotFx), Period.getCPtr(tenor), fixingDays, Calendar.getCPtr(calendar), (int)convention, endOfMonth, isFxBaseCurrencyCollateralCurrency), true) {
    if (NQuantLibcPINVOKE.SWIGPendingException.Pending) throw NQuantLibcPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
